# Generated by Django 5.2 on 2025-04-04 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='dimensions',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='size',
            field=models.CharField(default='N/A', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
