# Generated by Django 5.2 on 2025-04-06 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_productvariant_dimensions_productvariant_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Laukiama'), ('processing', 'Vykdoma'), ('shipped', 'Išsiųsta'), ('completed', 'Įvykdyta'), ('cancelled', 'Atšaukta')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products/'),
        ),
    ]
