# Generated by Django 5.2 on 2025-04-06 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_image',
        ),
    ]
