# Generated by Django 5.2 on 2025-04-08 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_userprofile_profile_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('slug', 'parent')},
        ),
    ]
